FROM python:3.8.13-buster

RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y

COPY server .
COPY requirements_backend.txt .

RUN pip3 install -r requirements_backend.txt

CMD ["python3","server/server.py"]