FROM mhart/alpine-node:15 AS builder
WORKDIR /app/
COPY objectdetector /app/
RUN npm i
RUN npm run build

FROM nginx:1.21.6 AS runner
WORKDIR /usr/share/nginx/html
run rm -rf ./*
COPY --from=builder /app/build .

EXPOSE 3000
EXPOSE 80

CMD ["/bin/sh" , "-c", "nginx -g 'daemon off;'"]

